# development settings
dev:
  ENV: "dev"
  PORT: 9001
  CLIENT_URL: http://localhost
  SERVER_URL: http://localhost
  SERVER_URI: http://localhost:9001
  devMode: true
  DB_URL: "mongodb://localhost"
  DB_PORT: 27017
  DB_NAME: "reimagined-train"
  SALT_ROUNDS: 9
  SESSION_SECRET: "12d17RATAJKOWSKI"
  AUTH_TOKEN_TITLE: "xxx-auth-token"
  ADMIN_AUTH_TOKEN_TITLE: "xxx-admin-auth-token"


prod:
  ENV: "prod"
  PORT: 9001
  CLIENT_PORT: 1234
  CLIENT_URL: https://uitestdonate.herokuapp.com
  SERVER_URL: http://localhost
  SERVER_URI: https://donatetoschool.herokuapp.com
  devMode: true
  DB_URL: "mongodb+srv://manish-baghel:q1w2e3r4@cluster0.mhnna.mongodb.net/reimagined-train?w=majority&retryWrites=true"
  DB_PORT: 27017
  DB_NAME: "reimagined-train"
  SALT_ROUNDS: 9
  SESSION_SECRET: "12d17RATAJKOWSKI"
  AUTH_TOKEN_TITLE: "xxx-auth-token"
  ADMIN_AUTH_TOKEN_TITLE: "xxx-admin-auth-token"

