# development settings
dev:
  ENV: "dev"
  PORT: 3001
  CLIENT_URL: http://localhost
  devMode: true
  DB_URL: "mongodb://localhost"
  DB_PORT: 27017
  DB_NAME: "reimagined-train"
  SALT_ROUNDS: 9
  SESSION_SECRET: "12d17RATAJKOWSKI"
  AUTH_TOKEN_TITLE: "auth-token"
  ADMIN_AUTH_TOKEN_TITLE: "auth-token"
  AWS_ACCESS_KEY: AKIAIWONG7BGRMYDV2BA
  AWS_SECRET_KEY: 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
  BUCKET_NAME: apidevtest.konfinity.com
  IMAGE_FOLDER: UPLOADS



